In [ ]:
# Teste - Jheni  
# Atividade 1 - Análise de dados com Python

In [2]:
# Importação de bibliotecas
import pandas as pd

In [27]:
# Lendo arquivos no excel
# df = Data Frame

df = pd.read_excel(r"C:\Users\Jhenifer Carvalho\Desktop\ExplorandoDadosv2\Planilhas\DataBase_v1 (1).xlsx",
    sheet_name="EQUIPE",
    usecols=["SENIORIDADE", "DESCRICAO_AT", "AUSENCIA_TIPO"],
)

df.head()
df

   DESCRICAO_AT SENIORIDADE AUSENCIA_TIPO
0     Consultor          Pr           NaN
1     Consultor          Sr           NaN
2     Consultor          Ex        FÉRIAS
3     Consultor          Sr           NaN
4     Consultor          Jr           NaN
..          ...         ...           ...
60    Consultor          Pr           NaN
61    Consultor          Sr           NaN
62    Consultor          Sr           NaN
63    Consultor          Pr           NaN
64    Consultor          Ex        FÉRIAS

[65 rows x 3 columns]

In [28]:
# DFS disponíveis no ambiente
%whos DataFrame

Variable    Type         Data/Info
----------------------------------
demandas    DataFrame    Shape: (1012, 16)
df          DataFrame    Shape: (65, 3)
df_merged   DataFrame    Shape: (1012, 23)
equipe      DataFrame    Shape: (65, 8)

In [29]:
#Verificando os tipos de senioridade
print(df["SENIORIDADE"].unique())

<StringArray>
['Pr', 'Sr', 'Ex', 'Jr', 'Bg']
Length: 5, dtype: str

In [30]:
# Filtrando os consultores do tipo Jr
consultor_Jr = df[df["SENIORIDADE"] == "Jr"]
consultor_Jr.head(100)

   DESCRICAO_AT SENIORIDADE AUSENCIA_TIPO
4     Consultor          Jr           NaN
5     Consultor          Jr           NaN
7     Consultor          Jr           NaN
11    Consultor          Jr           NaN
15    Consultor          Jr           NaN
16    Consultor          Jr           NaN
34    Consultor          Jr           NaN
37    Consultor          Jr           NaN
39    Consultor          Jr           NaN
45    Consultor          Jr           NaN

In [31]:
# Filtrando os consultores que estão ausentes por férias
consultores_Ausentes = df[df["AUSENCIA_TIPO"] == "FÉRIAS"]
consultores_Ausentes.head(60)

   DESCRICAO_AT SENIORIDADE AUSENCIA_TIPO
2     Consultor          Ex        FÉRIAS
13    Consultor          Sr        FÉRIAS
22    Consultor          Pr        FÉRIAS
25    Consultor          Sr        FÉRIAS
49    Consultor          Sr        FÉRIAS
51    Consultor          Ex        FÉRIAS
64    Consultor          Ex        FÉRIAS

In [32]:
# Verificando quais colunas existem no DataFrame
print(consultores_Ausentes.columns.tolist())

['DESCRICAO_AT', 'SENIORIDADE', 'AUSENCIA_TIPO']

In [33]:
# Filtrando somente os consultores do tipo Jr que estão ausentes por férias
consultores_Ausentes_Jr = df[(df["SENIORIDADE"] == "Jr") & (df["AUSENCIA_TIPO"] == "FÉRIAS")]
consultores_Ausentes_Jr.head(60)

Empty DataFrame
Columns: [DESCRICAO_AT, SENIORIDADE, AUSENCIA_TIPO]
Index: []

In [34]:
# Contagem de quantos consultores do tipo Jr estão ausentes por férias
consultores_Ausentes_Jr.count()

DESCRICAO_AT     0
SENIORIDADE      0
AUSENCIA_TIPO    0
dtype: int64

In [35]:
# Filtrando consultores do tipo Sr  estão ausentes por férias
consultores_Ausentes_Sr = df[(df["SENIORIDADE"] == "Sr") & (df["AUSENCIA_TIPO"] == "FÉRIAS")]
consultores_Ausentes_Sr.head(100)

   DESCRICAO_AT SENIORIDADE AUSENCIA_TIPO
13    Consultor          Sr        FÉRIAS
25    Consultor          Sr        FÉRIAS
49    Consultor          Sr        FÉRIAS

In [36]:
# Contagem de quantos consultores do tipo Sr estão ausentes por férias
consultores_Ausentes_Sr.count()

DESCRICAO_AT     3
SENIORIDADE      3
AUSENCIA_TIPO    3
dtype: int64

In [37]:
# Fazendo percentual relativo 
# Use len() para contar linhas corretamente
percentual_representativo = (len(consultores_Ausentes) / len(consultores_Ausentes_Sr)) * 100
print(f"{percentual_representativo:.2f}%")

233.33%

In [38]:
import pandas as pd
# Carregando as planilhas
demandas = pd.read_excel(r"C:\Users\Jhenifer Carvalho\Desktop\ExplorandoDadosv2\Planilhas\DataBase_v1 (1).xlsx",
    sheet_name="DEMANDAS")

equipe = pd.read_excel(r"C:\Users\Jhenifer Carvalho\Desktop\ExplorandoDadosv2\Planilhas\DataBase_v1 (1).xlsx",
     sheet_name="EQUIPE")

# Conferir o que foi carregado
print("DEMANDAS:", demandas.shape)
print("EQUIPE:", equipe.shape)

DEMANDAS: (1012, 16)
EQUIPE: (65, 8)

In [39]:
# IS é o ID do consultor, a chave comum entre DEMANDAS e EQUIPE
df_merged = demandas.merge(
    equipe,
    on="IS",        # chave em comum nas duas tabelas
    how="left"      # mantém todas as demandas
)

print(df_merged.shape)
df_merged.head(100)

(1012, 23)

,PROJETO,CHAMADO,Column1,DT_ABERTURA_CHAMADO,MODULO_CHAMADO,TIPO_CHAMADO,STATUS_CHAMADO,IS,CONSULTOR,MODULO_CustosNSULTOR,...,HORAS,TIPO_HORAS,COMPLEXIDADE,NOME,CODIGO_AT,DESCRICAO_AT,SENIORIDADE,AUSENCIA_INI,AUSENCIA_FIN,AUSENCIA_TIPO
0,PROJETO_01,TASK105721218-1,6,2024-03-25 11:29:08,Financeiro,Melhoria,UAT - M,ARDA2,Ali,Vendas,...,2.8,Horas Normais,N3,Ali,4890722-A0643,Consultor,Pr,NaT,NaT,NaN
1,PROJETO_01,TASK105614218-1,3,2023-12-11 08:59:42,Financeiro,Suporte,Closed,ASGN,Ari,Financeiro,...,1.4,Horas Normais,N1,Ari,4890722-A0644,Consultor,Sr,NaT,NaT,NaN
2,PROJETO_01,TASK105614218-1,3,2023-12-11 08:59:42,Financeiro,Suporte,Closed,ASGN,Ari,Financeiro,...,0.7,Horas Normais,N1,Ari,4890722-A0644,Consultor,Sr,NaT,NaT,NaN
3,PROJETO_01,TASK105614218-1,3,2023-12-11 08:59:42,Financeiro,Suporte,Closed,ASGN,Ari,Financeiro,...,2.1,Horas Normais,N1,Ari,4890722-A0644,Consultor,Sr,NaT,NaT,NaN
4,PROJETO_01,TASK105700511-1,5,2024-03-08 14:15:06,Financeiro,Suporte,Closed,ASGN,Ari,Financeiro,...,4.2,Horas Normais,N1,Ari,4890722-A0644,Consultor,Sr,NaT,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,PROJETO_01,TASK105692273-1,3,2024-02-27 07:50:00,Infra,Transporte,Closed,FANT,Fla,Infra,...,0.7,Horas Normais,N2,Fla,4890722-A0642,Consultor,Jr,NaT,NaT,NaN
96,PROJETO_01,TASK105692273-1,3,2024-02-27 07:50:00,Infra,Transporte,Closed,FANT,Fla,Infra,...,0.7,Horas Normais,N2,Fla,4890722-A0642,Consultor,Jr,NaT,NaT,NaN
97,PROJETO_01,TASK105692495-1,2,2024-02-27 12:36:11,Infra,Transporte,Closed,FANT,Fla,Infra,...,0.7,Horas Normais,N2,Fla,4890722-A0642,Consultor,Jr,NaT,NaT,NaN
98,PROJETO_01,TASK105693388-1,2,2024-02-29 09:00:14,Infra,Transporte,Closed,FANT,Fla,Infra,...,0.7,Horas Normais,N2,Fla,4890722-A0642,Consultor,Jr,NaT,NaT,NaN
99,PROJETO_01,TASK105690615-1,4,2024-02-26 05:49:46,Infra,Transporte,Closed,FANT,Fla,Infra,...,1.4,Horas Normais,N2,Fla,4890722-A0642,Consultor,Jr,NaT,NaT,NaN

In [ ]:
# Análise exploratória
# Total de demandas por consultor
df_merged.groupby("CONSULTOR")["CHAMADO"].count()

CONSULTOR
Aga      8
Ali      8
Ari      6
Arl     34
Ber     25
Car      9
Cin      3
Cla      5
Dav      8
Ede      6
Edi     16
Fel     15
Fla     26
Fra      4
Gab     20
Gis      5
Gle     14
Gra     39
Gui     18
Ith    175
Jan     45
Jef      9
Joa     50
Joc      1
Jon      4
Jor      3
Jos     18
Lan     38
Lea     15
Luc     25
Lui      6
Maj      8
Mar     49
Mic     97
Ota      3
Pat     13
Ped     11
Per      7
Pla     11
Raf      5
Raq     15
Ren     17
Rod     37
Rog      6
Sil     20
Thi      5
Tia     27
Val      8
Was     10
Wil      5
Name: CHAMADO, dtype: int64

In [18]:
# Demandas por tipo de chamado
df_merged.groupby("TIPO_CHAMADO")["CHAMADO"].count()

TIPO_CHAMADO
Manutenção    212
Melhoria      130
Perfis        225
Projetos      109
Suporte       309
Transporte     27
Name: CHAMADO, dtype: int64

In [23]:
# Chamados de complexidade N1
chamados_N1 = df_merged[df_merged["COMPLEXIDADE"] == "N1"]
chamados_N1

,PROJETO,CHAMADO,Column1,DT_ABERTURA_CHAMADO,MODULO_CHAMADO,TIPO_CHAMADO,STATUS_CHAMADO,IS,CONSULTOR,MODULO_CustosNSULTOR,...,HORAS,TIPO_HORAS,COMPLEXIDADE,NOME,CODIGO_AT,DESCRICAO_AT,SENIORIDADE,AUSENCIA_INI,AUSENCIA_FIN,AUSENCIA_TIPO
1,PROJETO_01,TASK105614218-1,3,2023-12-11 08:59:42,Financeiro,Suporte,Closed,ASGN,Ari,Financeiro,...,1.4,Horas Normais,N1,Ari,4890722-A0644,Consultor,Sr,NaT,NaT,NaN
2,PROJETO_01,TASK105614218-1,3,2023-12-11 08:59:42,Financeiro,Suporte,Closed,ASGN,Ari,Financeiro,...,0.7,Horas Normais,N1,Ari,4890722-A0644,Consultor,Sr,NaT,NaT,NaN
3,PROJETO_01,TASK105614218-1,3,2023-12-11 08:59:42,Financeiro,Suporte,Closed,ASGN,Ari,Financeiro,...,2.1,Horas Normais,N1,Ari,4890722-A0644,Consultor,Sr,NaT,NaT,NaN
4,PROJETO_01,TASK105700511-1,5,2024-03-08 14:15:06,Financeiro,Suporte,Closed,ASGN,Ari,Financeiro,...,4.2,Horas Normais,N1,Ari,4890722-A0644,Consultor,Sr,NaT,NaT,NaN
5,PROJETO_01,TASK105700511-1,5,2024-03-08 14:15:06,Financeiro,Suporte,Closed,ASGN,Ari,Financeiro,...,0.7,Horas Normais,N1,Ari,4890722-A0644,Consultor,Sr,NaT,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,PROJETO_02,TASK105682493-1,4,2024-02-20 13:55:26,Compras,Suporte,Closed,VLU,Val,Compras,...,5.6,Horas Normais,N1,Val,4890722-A0644,Consultor,Sr,NaT,NaT,NaN
1004,PROJETO_02,TASK105682493-1,4,2024-02-20 13:55:26,Compras,Suporte,Closed,VLU,Val,Compras,...,1.4,Horas Normais,N1,Val,4890722-A0644,Consultor,Sr,NaT,NaT,NaN
1008,PROJETO_02,TASK105664073-1,8,2024-02-01 06:47:46,Compras,Suporte,Closed,WPDM,Was,Custos,...,1.4,Horas Normais,N1,Was,4890722-A0645,Consultor,Ex,2024-04-01,2024-04-30,FÉRIAS
1010,PROJETO_02,TASK105721839-1,2,2024-03-26 07:07:31,Depósito,Suporte,Closed,T3JSM6,Jef,Depósito,...,4.2,Horas Normais,N1,Jef,4890712-Z0001,Consultor,Sr,NaT,NaT,NaN
1011,PROJETO_02,TASK105721839-1,2,2024-03-26 07:07:31,Depósito,Suporte,Closed,T3JSM6,Jef,Depósito,...,4.2,Horas Normais,N1,Jef,4890712-Z0001,Consultor,Sr,NaT,NaT,NaN

In [25]:
# Contando o número de chamados de complexidade N1
chamados_N1 = chamados_N1["CHAMADO"].count()
print(f"Número de chamados de complexidade N1: {chamados_N1}")

Número de chamados de complexidade N1: 626